#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.
# The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the commit.
#
# To enable this hook,
# rename this file to "pre-commit" inside the ".git/hooks" directory.

version=`astyle --version 2> /dev/null`
if test "x$version" != "x"; then
	ASTYLE=astyle
else
	version=`Tools/AStyle/astyle --version 2> /dev/null`
	if test "x$version" != "x"; then
		echo "git pre-receive hook: Did not find astyle, please install it before continuing."
		exit 1
	else
		ASTYLE=Tools/AStyle/astyle
	fi
fi
echo `$ASTYLE --version`

case `$ASTYLE --version 2> /dev/null` in
  Artistic*)
      ;;
  default)
      echo "git pre-commit hook: Did not find astyle, please install it before continuing."
      exit 1
      ;;
esac

ASTYLE_PARAMETERS_CPP="--style=kr \
    --indent=spaces=4 \
    --indent-classes \
    --indent-switches \
    --indent-namespaces \
    --indent-preprocessor \
    --indent-labels \
    --indent-col1-comments \
    --unpad-paren \
    --keep-one-line-blocks \
    --keep-one-line-statements \
    --lineend=linux \
    --suffix=none"

FILES=`git-diff-index --diff-filter=ACMR --name-only -r --cached $against --`
echo $FILES > Tools/AStyle/files.txt
FILES_CPP=`sed -n -e '/^.*\\.cpp\$/p' Tools/AStyle/files.txt`
$ASTYLE ${ASTYLE_PARAMETERS_CPP} $FILES_CPP

# to be expanded later.
